force-app/main/default/objects/Marketing_Email_Request__c/Marketing_Email_Request__c.object-meta.xml
<CustomObject>
    <label>Marketing Email Request</label>
    <nameField>
        <displayFormat>MER-{00000}</displayFormat>
        <label>Marketing Email Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Marketing Email Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Marketing_Email_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Marketing Email Requests</relationshipLabel>
    <relationshipName>Marketing_Email_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Email_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Marketing Email Requests</relationshipLabel>
    <relationshipName>Marketing_Email_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Marketing_Email_Request__c/fields/Section_1_Image_Customer_Key__c.field-meta.xml
<CustomField>
    <fullName>Section_1_Image_Customer_Key__c</fullName>
    <label>Section 1 Image Customer Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Email_Request__c/fields/Section_2_Image_Customer_Key__c.field-meta.xml
<CustomField>
    <fullName>Section_2_Image_Customer_Key__c</fullName>
    <label>Section 2 Image Customer Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Marketing_Email_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Sending</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Marketing_Email_Request__c/fields/Template_Customer_Key__c.field-meta.xml
<CustomField>
    <fullName>Template_Customer_Key__c</fullName>
    <label>Template Customer Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MarketingEmailRequest_Controller_Test.cls
@isTest
public class MarketingEmailRequest_Controller_Test {
    static testMethod void unitTest1() {
        INFW_TestHelper helper = new INFW_TestHelper();
        
        Date today = Date.today();
        DateTime now = DateTime.now();
            
        User user1 = helper.createUser('System Administrator', 'Test', 'Tsakiridis', '');
        user1.MobilePhone = '0417652342';
        user1.Email = 'tass_tsakiridis@b-f.com';
        user1.Market__c = 'Australia';
        insert user1;
                
        Market__c mAU = helper.createMarket('Australia');
        mAU.Vistex_Clearing_Account__c = '0123456789';
        Market__c[] marketList = new Market__c[]{mAU};
        insert marketList;
        
        System.runAs(user1) {
            Account account1 = helper.createAccount('TestAccount1', mAU.Id, 'Off');
            Account[] accountList = new Account[]{account1};
            insert accountList;
                    
            Contact contact1 = helper.createContact('Tass', 'Tsakiridis', account1.Id);
            insert contact1;

            AccountPagedResult accounts = MarketingEmailRequest_Controller.getAccounts('', '', '', '', '', 1);
            System.assertNotEquals(null, accounts, 'Account have been found');
            
            List<ContentVersion> files = MarketingEmailRequest_Controller.getMaterials();
            System.assertNotEquals(null, files, 'Files have been found');
            
            User thisUser = MarketingEmailRequest_Controller.getUserDetails();
            System.assertNotEquals(null, thisUser, 'User details have been found');
            
            List<String> templates = MarketingEmailRequest_Controller.getTemplates();
            
            Marketing_Email_Request__c mer = new Marketing_Email_Request__c();
            mer.Account__c = account1.Id;
            mer.Contact__c = contact1.Id;
            mer.Status__c = 'New';
            mer.Template_Customer_Key__c = 'c76f6503-fd71-4289-91ed-502d4c9c3a53';
            mer.Section_1_Image_Customer_Key__c = 'http://image.S7.exacttarget.com/lib/fe9013727c660d7f75/m/1/30d8baa3-a738-444d-b0c5-4503b21dc6fa.gif';
            mer.Section_2_Image_Customer_Key__c = 'http://image.S7.exacttarget.com/lib/fe9013727c660d7f75/m/1/2b9b9bc9-80c5-412e-ba8b-2bc858a3b75d.gif';
            
            List<Marketing_Email_Request__c> requests = new List<Marketing_Email_Request__c>();
            requests.add(mer);
            
            requests = MarketingEmailRequest_Controller.submitRequest(requests);
        }
    }
}